name: Compilation test

on:
  push:

jobs:
  run-jpf:
    runs-on: ubuntu-20.04
    name: Run Compilation

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 1.8
    - name: Set up Maven
      uses: actions/setup-java@v2
      with:
        java-version: 1.8
        maven-version: 2.0.31
    - name: Compile Java sources
      run: |
        mvn clean install -DskipTests
        
