name: Compilation test

on:
  push:

jobs:
  run-jpf:
    runs-on: ubuntu-20.04
    name: Run Compilation

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 11
    - name: Set up Maven
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 11
        maven-version: 3.6.3
    - name: Compile Java sources
      run: |
        mvn clean install -DskipTests
        
